[tool.poetry]
name = "gqlapi"
version = "0.1.0"
description = "Alima's GraphQL API"
authors = ["jorgeviz"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
strawberry-graphql = "^0.170.0"
uvicorn = "^0.21.1"
starlette = "^0.26.1"
sqlalchemy = "~1.4.42"
databases = "^0.7.0"
firebase-admin = "^6.1.0"
motor = "^3.1.2"
openpyxl = "^3.1.2"
pandas = "^2.0.1"
python-multipart = "^0.0.6"
bs4 = "^0.0.1"
lxml = "^4.9.2"
cloudinary = "^1.33.0"
algoliasearch = "^3.0.0"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
tqdm = "^4.66.1"
xlsxwriter = "^3.1.9"
fuzzywuzzy = "^0.18.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"
autopep8 = "^2.0.2"
logger = {path = "../../lib/logger", develop = true}
metrics = {path = "../../lib/metrics", develop = true}
environ = {path = "../../lib/environ", develop = true}
future = {path = "../../lib/future", develop = true}
domain = {path = "../../domain", develop = true}
postgres = {path = "../../lib/postgres", develop = true}
application = {path = "../../lib/application", develop = true}
clients = {path = "../../lib/clients", develop = true}
integrations = {path = "../../lib/integrations", develop = true}
pytest-env = "^0.8.1"
tqdm = "^4.66.1"


[tool.poetry.group.dev-linux.dependencies]
black = "^23.3.0"

[tool.poetry.scripts]
api-server = "gqlapi.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
